### ISSUE TITLE
Inverter Design Question + Hello

### ISSUE THREAD

**Issue by tyVandeZande** [benkrasnow/EL_driver_multi#3]
Hi, first, this is so so awesome. Thank you!

Second I have been working with EL screen printing and airbrushing for a few years– I've run into and troubleshooted most every possible problem with the materials! If anyone has questions about issues with application process or bizarre defects ((there can be many weird issues with EL)) — Feel free to reach out!

Third Inverter Design– I have no engineering background and am self teaching electronics from your videos + others on youtube. So please forgive me if I am missing some trivial//obvious electronics knowledge.

Does Pin 3 on the transformer need to be tied to GND? It seems safer for a person if the HV is isolated, rather than connected to GND. It looks like in the current design, if someone accidentally touches The EL and some other piece of the circuit (including batteries or a computer this is plugged into), the circuit would short through the user. Am I mistaking?

Also, what is the purpose of D3/D4 MMBD004S ?

Thank you so much for your time and contributions!

<img width="730" alt="Screen Shot 2020-09-09 at 6 45 41 PM" src="https://user-images.githubusercontent.com/53837387/92663272-c88ba080-f2ce-11ea-9277-1abbb75dd939.png">

**Comment by benkrasnow** [comment]
In my original application, the EL segments were controlled by a switching IC, which requires a high voltage DC rail (up to 300V), and this rail must be referenced to GND, the same GND as the logic control of the IC.  This is why pin 3 of the transformer ATB3225 is grounded.  The diode MMBD5004 rectifies the AC into a pulsating DC, which is smoothed by a capacitor that was shown on my original schematic.  Two diodes are in series so that their rated blocking voltages are summed together.  Diode B0540 prevents pin 1 of LT3468 from undershooting GND due to inductive kick from the switchmode control of the transformer.  

If you want to run a single EL panel directly from the transformer without the switching IC, you can probably connect it directly to the transformer and not ground pin 3.

**Comment by tyVandeZande** [comment]
Okay, gotcha Re: Pin3. If the HVGND is never referenced to GND, it could cause errors in the gates in the switching IC because the logic gates are "riding" and variable voltage? I believe I've heard someone call that a ground loop interference before? 

In my previous controller designs, I've been using an array of triacs to control each segment–using the triacs basically as a relay (schematic attached) This design has two separate power sources, one for inverter and one for the logic. In my schematic, if there is an unstable connection between an EL segment and the triac, my Teensy freaks, spits gibberish over Serial, then restarts ((Teensy hasn't bricked yet)) – But if theres a stable connection, the program runs fine for a while! Hah.

Diodes: That totally makes sense, thanks again!
<img width="1288" alt="Screen Shot 2020-09-09 at 9 55 07 PM" src="https://user-images.githubusercontent.com/53837387/92673359-eebe3a00-f2e8-11ea-9946-1a869c0363aa.png">
